# Generated by Django 2.0.7 on 2018-07-18 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0007_auto_20180718_0714'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='exams.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='persons.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('student', 'exam')},
        ),
    ]
