# Generated by Django 2.0.7 on 2018-07-16 10:00

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(max_length=10, unique=True, verbose_name='global id')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[(persons.models.Gender('m'), 'Homme'), (persons.models.Gender('f'), 'Femme')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
    ]
