# Generated by Django 2.0.7 on 2018-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('m', 'Homme'), ('f', 'Femme')], max_length=1),
        ),
    ]
