# Generated by Django 2.0.7 on 2018-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20180716_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
    ]
