# Generated by Django 2.0.7 on 2018-07-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='functions.Function'),
        ),
    ]
