# Generated by Django 2.0.7 on 2018-07-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20180717_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('persons.person',),
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('a', 'Staff'), ('b', 'Student')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='student_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='persons.Person'),
        ),
    ]
